using System;
using System.IO;

namespace BankomatApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Bankomat bankomat = new Bankomat();
            bankomat.Run();
        }
    }

    class Bankomat
    {
        private Konto konto;
        private const string plikBazy = "baza.txt";

        public Bankomat()
        {
            konto = new Konto(plikBazy);
        }

        public void Run()
        {
            while (true)
            {
                Console.WriteLine("\n1. Sprawdź saldo\n2. Wpłać\n3. Wypłać\n4. Wyjdź");
                Console.Write("Wybierz opcję: ");
                string wybor = Console.ReadLine();

                switch (wybor)
                {
                    case "1":
                        Console.WriteLine($"Twoje saldo: {konto.Saldo} PLN");
                        break;
                    case "2":
                        Console.Write("Podaj kwotę wpłaty: ");
                        if (decimal.TryParse(Console.ReadLine(), out decimal wplata) && wplata > 0)
                        {
                            konto.Wplac(wplata);
                        }
                        else
                        {
                            Console.WriteLine("Błąd: niepoprawna kwota.");
                        }
                        break;
                    case "3":
                        Console.Write("Podaj kwotę wypłaty: ");
                        if (decimal.TryParse(Console.ReadLine(), out decimal wyplata) && wyplata > 0)
                        {
                            konto.Wyplac(wyplata);
                        }
                        else
                        {
                            Console.WriteLine("Błąd: niepoprawna kwota.");
                        }
                        break;
                    case "4":
                        Console.WriteLine("Dziękujemy za skorzystanie z bankomatu.");
                        return;
                    default:
                        Console.WriteLine("Niepoprawny wybór. Spróbuj ponownie.");
                        break;
                }
            }
        }
    }

    class Konto
    {
        public decimal Saldo { get; private set; }
        private string plik;

        public Konto(string plik)
        {
            this.plik = plik;
            WczytajSaldo();
        }

        public void Wplac(decimal kwota)
        {
            Saldo += kwota;
            ZapiszSaldo();
            Console.WriteLine($"Wpłacono {kwota} PLN. Nowe saldo: {Saldo} PLN");
        }

        public void Wyplac(decimal kwota)
        {
            if (Saldo >= kwota)
            {
                Saldo -= kwota;
                ZapiszSaldo();
                Console.WriteLine($"Wypłacono {kwota} PLN. Nowe saldo: {Saldo} PLN");
            }
            else
            {
                Console.WriteLine("Błąd: Niewystarczające środki na koncie!");
            }
        }

        private void WczytajSaldo()
        {
            if (File.Exists(plik))
            {
                string zawartosc = File.ReadAllText(plik);
                if (decimal.TryParse(zawartosc, out decimal saldo))
                {
                    Saldo = saldo;
                }
                else
                {
                    Console.WriteLine("Błąd: Niepoprawna zawartość pliku bazy. Resetowanie salda do 1000 PLN.");
                    Saldo = 1000m;
                    ZapiszSaldo();
                }
            }
            else
            {
                Saldo = 1000m;
                ZapiszSaldo();
            }
        }

        private void ZapiszSaldo()
        {
            File.WriteAllText(plik, Saldo.ToString());
        }
    }
}
